version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "dev"
    versioning-strategy: "widen"
    schedule:
      interval: "weekly"
    labels:
      - "C-dependencies"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/bluebird-hmi"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    labels:
      - "C-dependencies"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
