site_name: bluebird-dt

plugins:
  - macros:
       modules: [docs.get_version]

nav:
  - Getting started with bluebird-dt: getting-started.md
  - Available airspace:
      - airspace/index.md
      - I-sector: airspace#i-sector
      - Y-sector: airspace#y-sector
      - X-sector: airspace#x-sector
      - Xplus-sector: airspace#xplus-sector
      - Springfield: airspace#springfield
  - Available scenarios:
      - scenarios/index.md
      - Infinite: scenarios#infinite
      - Springfield: scenarios#springfield
      - Two Aircraft: scenarios#two-aircraft
      - Regular: scenarios#regular
  - Digital twin concepts:
      - design/index.md
      - Core classes: design#core-classes
      - Scenario and airspace generators: design#scenario-and-airspace-generators
      - Simulation and event management: design#simulation-and-event-management
      - Predictors: design#predictors
      - Utility functions: design#utility-functions
  - Examples with bluebird-dt:
    - Simulation example: examples/Intro-Part-1.ipynb
    - Simulation example: examples/Intro-Part-2.ipynb
    - Simulation example: examples/Intro-Part-3.ipynb
    - Simulation example: examples/Intro-Part-4.ipynb
    - Radar visualisation: examples/render/radar.ipynb
  - Source reference: source.md
