site_name: bluebird-dt

plugins:
  - macros:
       modules: [docs.get_version]

nav:
  - Getting started with bluebird-dt: getting-started.md
  - Available airspace:
      - airspace.md
      - Sectors:
          - I-sector: ./airspace.md#i-sector
          - Y-sector: ./airspace.md#y-sector
          - X-sector: ./airspace.md#x-sector
          - Xplus-sector: ./airspace.md#xplus-sector
          - Springfield: ./airspace.md#springfield
  - Available scenarios:
      - scenarios.md
      - Two Aircraft: ./scenarios.md#two-aircraft
      - Regular: ./scenarios.md#regular
      - Custom: ./scenarios.md#custom
      - Infinite: ./scenarios.md#infinite
  - Digital twin concepts:
      - design.md
      - Core classes: ./design.md#core-classes
      - Scenario and airspace generators: ./design.md#scenario-and-airspace-generators
      - Simulation and event management: ./desing.md#simulation-and-event-management
      - Predictors: ./design.md#predictors
      - Utility functions: ./design.md#utility-functions
  - Examples with bluebird-dt:
    - Simulation example: examples/Intro-Part-1.ipynb
    - Simulation example: examples/Intro-Part-2.ipynb
    - Simulation example: examples/Intro-Part-3.ipynb
    - Simulation example: examples/Intro-Part-4.ipynb
    - Radar visualisation: examples/render/radar.ipynb
  - API reference: source.md
