site_name: bluebird-api

nav:
  - Getting started with bluebird-api: getting-started.md
  - Examples with bluebird-api:
    - Using bluebird-api with a non-python agent: examples/NonPythonAgents.ipynb
  - Source reference: source.md
