site_name: Project Bluebird documentation
site_url: https://docs.projectbluebird.ai
repo_url: https://github.com/project-bluebird/BluebirdATC
repo_name: project-bluebird/BluebirdATC
docs_dir: src
site_dir: ../site
dev_addr: 127.0.0.1:8010
watch:
  - ../bluebird-dt/docs
  - ../bluebird-api/docs
  - ../bluebird-gymnasium/docs
  - ../bluebird-hmi/docs
  - ../bluebird-dt/bluebird_dt
  - ../bluebird-api/bluebird_api
  - ../bluebird-gymnasium/bluebird_gymnasium
  - ../bluebird-dt/mkdocs.yml
  - ../bluebird-api/mkdocs.yml
  - ../bluebird-gymnasium/mkdocs.yml
  - ../bluebird-hmi/mkdocs.yml
extra_css:
  - stylesheets/nav.css

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: custom
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: custom
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
  features:
    - navigation.instant
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.indexes
    - navigation.sections


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-jupyter:
      include:
        - "*.ipynb"
      include_source: true
  - monorepo
  - mkdocstrings:
       handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true

validation:
  nav:
    omitted_files: ignore
    not_found: ignore

nav:
  - Project Bluebird: index.md
  - Neurips competition: examples/competition/Competition-Intro.ipynb
  - User guide:
    - Getting started: getting-started.md

    - ATC concepts:
        - atc/index.md
        - Airspace: atc/airspace.md
        - Aircraft: atc/aircraft.md
        - Clearances: atc/clearances.md
        - Coordinations: atc/coordinations.md

  - bluebird-dt: "!include ../bluebird-dt/mkdocs.yml"

  - bluebird-api: "!include ../bluebird-api/mkdocs.yml"

  - bluebird-gymnasium: "!include ../bluebird-gymnasium/mkdocs.yml"

  - bluebird-hmi: "!include ../bluebird-hmi/mkdocs.yml"

  - Development:
    - How to contribute: how-to-contribute.md
    - Docs:
      - Intro: mkdocs-guide/#intro
      - Serve the docs locally: mkdocs-guide/#serve-the-docs-locally
      - Build the docs for production: mkdocs-guide/#build-the-docs-for-production
      - File hierarchy: mkdocs-guide/#file-hierarchy
      - Example edit-serve-build workflow: mkdocs-guide/#example-edit-serve-build-workflow
