---
name: BluebirdATC linting and tests

on:
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  ubuntu-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.10"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up cache
        uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock') }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Display Python version
        run: uv run python -c "import sys; print(sys.version)"

      - name: Check linting
        run: uv run ruff check bluebird-api bluebird-dt bluebird-gymnasium docs --output-format=github

      - name: Check formatting
        run: uv run ruff format bluebird-api bluebird-dt bluebird-gymnasium docs --check --diff

      - name: Check testing
        run: uv run pytest -n auto --cov=. --cov-report=xml

      - name: Upload coverage report
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: coverage.xml
          language: Python
          label: code-coverage/pytest
